root = "."
tmp_dir = "tmp"

[build]
cmd = "task build DEBUG=off"
post_cmd = ["cp config.docker.json bin/config.json"]

bin = "bin/scylladbtest"
args_bin = ["-config", "bin/config.json", "-time-frame", "1s", "-requests", "100", "-parallelism", "100"]

include_ext = ["go", "yml", "json", "toml"]
exclude_dir = ["public", "vendor", "log", "tmp"]
exclude_file = ["Dockerfile"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
